@startuml
'https://plantuml.com/sequence-diagram

class ToDoListMain{
   + main(): void
   + start(): void
}

class Item{
 String itemDescription;
 Date dueDate ;
 Boolean itemDone;

+Item()
 + getItemDescription() : String
 + setItemDescription(String itemDescription) : void
 +Date getDueDate() : Date
 + setDueDate(Date dueDate) : void
 + setItemDone(Boolean itemDone): void

}

class EditItemPageController {

#TextFiled itemDescription
#DatePicker itemDate
#Item item
+initialize(URL url, ResourceBundle resourceBundle): void
-loadItem() : void
+setItem (Item item): void
-showErrorAlert(String title, String text): void
-showSuccessAlert(String title, String text): void

}






class ToDoListPageController {
+ modifyListName(ActionEvent actionEvent): void
+ displayOptions(ActionEvent actionEvent): void
+ addItemtoList(ActionEvent actionEvent): void
+ addItemName(ActionEvent actionEvent) : void
+ addItemDueDate(ActionEvent actionEvent): void
+ displayItem (ActionEvent actionEvent): void
+  deletItem(ActionEvent actionEvent): void
+ SaveLocalStirage(ToDo todo) : void
+ markItemAsDone(ActionEvent actionEvent) :void
+ deleteEntireToDoList(ActionEvent actionEvent): void
+ saveList(ActionEvent actionEvent) : void
+ openEditItemPage(ActionEvent actionEvent): void
+  displayAll(ActionEvent actionEvent): void
+ displayCompleted(ActionEvent actionEvent): void
+ displayIncomplete(ActionEvent actionEvent): void



}

javafx.Application <|-- ToDoListMain
java.io.Serializable<|--Item
javafx.Initializable<|--EditItemPageController
ToDoListPageController -- ToDoListMain
Item<-EditItemPageController
Item<-ToDoListPageController

DisplayAllController - EditItemPageController
DisplayCompletedController - EditItemPageController
DisplayIncompletedListController - EditItemPageController
EditItemPageController -- ToDoListPageController
ToDoListPageController -- ToDoListController

@enduml